name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # Make sure this is the build command for your project

      - name: Upload artifact
        id: build
        uses: actions/upload-artifact@v2
        with:
          name: github-pages
          path: ./dist  # Adjust this path if your build output is different

  deploy:
    needs: build  # Ensure the deploy job runs after the build job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_id: ${{ needs.build.outputs.artifact_id }}
          pages_build_version: ${{ needs.build.outputs.pages_build_version }}

    environment:
      name: github-pages  # Specify the environment for deployment
