name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

permissions:
  contents: read  # Default permission for reading the repository
  id-token: write  # Grant write access to the id-token for Pages deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Specify Node.js version 18 or higher

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # Ensure this is the correct build command for your project

      - name: Upload artifact
        id: build
        uses: actions/upload-artifact@v3
        with:
          name: github-pages  # Artifact name must be the same as in the deploy step
          path: ./dist        # Adjust this path if your build output is different

  deploy:
    needs: build  # Ensure the deploy job runs after the build job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the GITHUB_TOKEN for authentication
          artifact_name: github-pages  # Specify the artifact name uploaded in the previous step

    environment:
      name: github-pages  # Specify the environment for deployment
